### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### GitHub Corrected URLs 
Was | Now 
--- | --- 
https://github.com/jakearchibald/es6-promise/ | https://github.com/stefanpenner/es6-promise 

### HTTPS Corrected URLs 
Was | Now 
--- | --- 
http://en.wikipedia.org/wiki/Cross-Origin_Resource_Sharing#Browser_support | https://en.wikipedia.org/wiki/Cross-Origin_Resource_Sharing#Browser_support 
http://en.wikipedia.org/wiki/JSONP | https://en.wikipedia.org/wiki/JSONP 
http://github.com/algolia/algoliasearch-client-js | https://github.com/algolia/algoliasearch-client-js 
http://img.shields.io/badge/license-MIT-green.svg?style=flat-square | https://img.shields.io/badge/license-MIT-green.svg?style=flat-square 

### Other Corrected URLs 
Was | Now 
--- | --- 
https://npmcdn.com/algoliasearch@3/dist/algoliasearch.min.js | https://npmcdn.com/algoliasearch@3.13.1/dist/algoliasearch.min.js 
https://npmjs.org/package/algoliasearch | https://www.npmjs.com/package/algoliasearch

### CODE REVIEW

**Comment by vvo** [comment]
We use a readme generator

**Comment by ReadmeCritic** [comment]
@vvo oh ic

**Comment by ReadmeCritic** [comment]
@vvo anyway, let me know if you'd like me to update the readme source file

**Comment by vvo** [comment]
Yes, but you should do it here: https://github.com/algolia/algoliasearch-client-readme-generator/

**Pull request closed without merging**
