### PR TITLE
Provides a react native build

### PR DESCRIPTION
**Pull request by bobylito**

### CODE REVIEW

**Comment by redox** [comment]
Looks great @bobylito. Did you build a sample app as well? Would be cool to link to an example from the README.

**Comment by bobylito** [comment]
I have a sample project working as well but it definitely need some polish because it is a bit raw right now. I will push it on another repository if you're ok with that.

**Comment by vvo** [comment]
Well looks awesome! I wonder how could we test that. For now it's "beta" I guess and code is mostly the browser build without JSONP etc..

**Comment by vvo** [comment]
@bobylito Feel free to release this

**Comment by vvo** [comment]
> I will push it on another repository if you're ok with that.

Would be cool so that we can point people to it on demand

**Pull request merged**
