### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by algoliareadmebot**
PR

### CODE REVIEW

**Comment by vvo** [comment]
I don't get why PRS are opened then closed @CBaptiste

**Comment by CBaptiste** [comment]
I need to compute the name of the PR based on the commit linked to the PR, and the easiest way to list the commits linked to a PR with the github API is it fetch it from an existing PR.
so: 1. I create the PR 2. get the commit list and get the name 3. close it and create it with the new name (I cannot directly upate the name unfortunately)
Is it ok ?

**Comment by pixelastic** [comment]
It adds a lot of noise, I'd really prefer if we can get rid of the first PR and only keep one.

**Comment by CBaptiste** [comment]
yes @pixelastic, this is fixed :)

**Pull request closed without merging**
