### PR TITLE
Syntax errors on examples in README.md

### PR DESCRIPTION
**Pull request by mekza**
According to https://www.algolia.com/doc/javascript#MultiQuery

### CODE REVIEW

**Comment by vvo** [comment]
Hi thanks for this. Both syntaxes should work, I assume it did not work for you?

**Comment by mekza** [comment]
It didn't work for me, I get  `Uncaught SyntaxError: Unexpected token {`

**Comment by vvo** [comment]
oh yeah sorry it was a syntax error. I first thought you proposed to use {params: query}, it would also have worked.

We have a dedicated project for all api docs: https://github.com/algolia/algoliasearch-client-readme-generator/blob/master/include/JavaScript/multiple_queries.snippet

either we will do the change here or if you are up to, please do it ;)

thanks a lot! Hope you like our new JavaScript client.

**Comment by mekza** [comment]
I didn't see this dedicated repository, I'm doing changes in this one.

**Pull request closed without merging**
