### PR TITLE
feat(build): provide a lite build

### LINKED ISSUE #215: Client is heavyweight
Hi, I noticed that adding the client to my application added 70kb to the minified build. Is that normal?
Could we split the client to have only the minimal code on the client?

### PR DESCRIPTION
**Pull request by vvo**
Now providing a lite browser build:
- search only
- vanilla JS only (no angular, jquery lite builds for now)
- same export name (`algoliasearch`)
- now 5.93kb gzipped (versus 20kb)
- IE11/10/9 not natively supported, use http://cdn.polyfill.io/v2/docs/
  or just provide the Promise polyfill in the global object (window)
- same init usage
- has
  client.search/index.search/clearCache/setRequestTimeout/setExtraHeader/..
- no write/indexing/waitTask/settings methods => search only
- available on jsDelivr using algoliasearchLite[.min].js
- also requireable using
  var algoliasearch = require('algoliasearch/dist/algoliasearchLite.js');

fixes #215

### CODE REVIEW

**Comment by redox** [comment]
That's awesome @vvo!

**Comment by vvo** [comment]
5.93kb

:dancers: 

We can have IE9/10/11 compat but it would weight something like 7-8kb, what do you think?

**Comment by vvo** [comment]
It's 8KB with the Promise polyfill. I will not do it for now, let's wait for some users to ask for it before making plans

**Comment by anaibol** [comment]
Personally I prefer without polyfills. ES6 modules make it easy to add extra polyfills if required.

**Comment by vvo** [comment]
So this is passing tests, lets wait monday morning for a release :)

**Comment by anaibol** [comment]
By the way, how can we "ES6 import" this lite version? Maybe it should be a separate NPM package.

**Comment by vvo** [comment]
`import 'algoliasearch' from 'algoliasearch/dist/algoliasearchLite.js'` should do it.. once released.

In the meantime you should be able to build it yourself if you want:

```
npm install
NODE_ENV=production npm run build
```

**Comment by anaibol** [comment]
Great!

**Comment by redox** [comment]
> We can have IE9/10/11 compat but it would weight something like 7-8kb, what do you think?

Are we able to add the Promise polyfill only for the `<script>` build? If so I would go that way!

**Pull request merged**
