### PR TITLE
fix: CORS simple request for all browser builds

### LINKED ISSUE #111: angularjs build issues OPTIONS request
see #24

### PR DESCRIPTION
**Pull request by vvo**
We were not setting the right headers previously
    
Now setting
  - accept: application/json and
  - content-type: 'application/x-www-form-urlencoded' (POST)
  - content-type: 'application/json' (PUT)
    
fixes #111

### CODE REVIEW

**Comment by vvo** [comment]
cc @speedblue @redox

**Comment by redox** [comment]
LGTM if the integration tests are saying so :)

**Comment by vvo** [comment]
Yes, waiting for them, integration tests ran on my machine OK, now onto travis.

Integration tests are not checking if there's an OPTION request being made, unit test does.

Because you cannot intercept an OPTION request nor test it :-)

**Comment by redox** [comment]
:+1:

**Pull request merged**
