### PR TITLE
feat: new generateSecuredApiKey(apiKey, queryParameters)

### PR DESCRIPTION
**Pull request by vvo**

### CODE REVIEW

**Comment by Nagriar** [comment]
@vvo You can also convert the old tagFilters to the new version:
- if it contains a '=' it's already a url encoded query parameters => new version
- if it's an array or a string => convert to { 'tagFilters': value} => new version

**Comment by vvo** [comment]
Yes indeed I forgot that you could also call generateSecuredApiKey(key, tagFiltersAsString), is that what you meant?

**Comment by vvo** [comment]
@Nagriar Not sure to get why we would want to convert every usage to the new key format, won't this introduce some errors because people update the client and still set the x-algolia-query-params?

**Comment by vvo** [comment]
@Nagriar this is ready and doc has been updated, can you have a last look

**Comment by Nagriar** [comment]
No if you use the new format, the x-algolia-query-params is ignored. The new format is simpler to use and to debug. I'd prefer to convert the old tagFilters to the new format too.

**Comment by vvo** [comment]
understood, will change this

**Comment by vvo** [comment]
updated the PR

**Comment by vvo** [comment]
@Nagriar, updated, with unit and functional tests

**Comment by Nagriar** [comment]
great job @vvo!

**Comment by vvo** [comment]
Let's merge this baby

**Pull request merged**
