### PR TITLE
Updated README (prepare algolia.com's integration)

### PR DESCRIPTION
**Pull request by redox**
cc @alexandremeunier

### CODE REVIEW

**Comment by vvo** [comment]
woa, shiny. Will we be able to have a list of methods at some point on top of this? Rather than use cases list. I guess once you are here what you are looking for is a method list. Dunno if that's doable given all the various API clients still

**Comment by vvo** [comment]
But it's already a looooooooot better than previously :)

**Comment by alexandremeunier** [comment]
@vvo: 100% agree. We need a more explicit method list. That's my next step :)

**Comment by redox** [comment]
@vvo yeah, the method list is supposed to be  
screen shot 2016-03-29 at 15 01 26


but indeed, it's not code.

**Comment by redox** [comment]
Not sure why the tests are failing :/

```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```

Saucelabs issue?

**Comment by vvo** [comment]
Yeah saucelabs issue.

@redox what I meant by method list is this:

- index.setSettings
- index.getSettings
- index.search
- client.search
- index.getObject
- client.batch
- ...

So that once you already know the client (and if you are on github, there's a high probability you already know it) then you do not have to map "Ah so I am looking for index.getSettings usafe, let's find where it is in this list".

I agree this may no be done easily with what we have. But this is ultimately what I am looking for when I am on our API client github projects: the API list, not use cases.

This is similar to instantsearch.js where in the menu we have "searchBox" versus "add a search input"

**Comment by vvo** [comment]
This can be merged without any issue

**Comment by vvo** [comment]
LGTM

**Pull request merged**
