### PR TITLE
fix(searchFacet): rename searchFacet to searchForFacetValues

### PR DESCRIPTION
**Pull request by vvo**

### CODE REVIEW

**Comment by bobylito** [comment]
Documentation is not updated with the same way of describing the feature

**Comment by vvo** [comment]
did it in a backward compat way, updated the jsDoc

**Comment by bobylito** [comment]
👍 I think we're good to go. Since there are tests for both methods, it seems pretty safe to merge (and even release, no?)

**Comment by vvo** [comment]
> I think we're good to go. Since there are tests for both methods, it seems pretty safe to merge (and even release, no?)

Let's do this yes

**Pull request merged**
